import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">DashboardFive</Link>
        </li>
        <li>
          <Link to="/projectlibrary">ProjectLibrary</Link>
        </li>
        <li>
          <Link to="/dashboardsix">DashboardSix</Link>
        </li>
        <li>
          <Link to="/algorithmselection">AlgorithmSelection</Link>
        </li>
        <li>
          <Link to="/clusteranalysis">ClusterAnalysis</Link>
        </li>
        <li>
          <Link to="/algorithmselectionone">AlgorithmSelectionOne</Link>
        </li>
        <li>
          <Link to="/whitespaceanalysis">WhitespaceAnalysis</Link>
        </li>
        <li>
          <Link to="/productcharacteristics">ProductCharacteristics</Link>
        </li>
        <li>
          <Link to="/productrecomendations">ProductRecomendations</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
